// Package generator renders CoreDNS zone files and Corefiles from a records
// Config. The functions are pure (input -> string) so they are easy to test;
// callers are responsible for writing the results to disk.
package generator

import (
	"fmt"
	"strings"

	"dev-dns/internal/records"
)

// Zone renders an RFC 1035 master zone file for cfg using the given SOA serial.
// The caller typically passes a monotonically increasing serial (e.g. the Unix
// time) so CoreDNS's file plugin notices the change and reloads.
func Zone(cfg *records.Config, serial uint32) string {
	zone := cfg.Zone
	ttl := cfg.ResolvedTTL()

	var b strings.Builder
	b.WriteString("; Generated by devdns -- do not edit by hand.\n")
	b.WriteString("; Edit records.yaml and run `devdns generate` instead.\n")
	fmt.Fprintf(&b, "$ORIGIN %s.\n", zone)
	fmt.Fprintf(&b, "$TTL %d\n", ttl)
	fmt.Fprintf(&b, "@\tIN\tSOA\tns.%s. admin.%s. (\n", zone, zone)
	fmt.Fprintf(&b, "\t\t\t%d\t; serial\n", serial)
	b.WriteString("\t\t\t7200\t; refresh\n")
	b.WriteString("\t\t\t3600\t; retry\n")
	b.WriteString("\t\t\t1209600\t; expire\n")
	fmt.Fprintf(&b, "\t\t\t%d )\t; minimum\n", ttl)
	fmt.Fprintf(&b, "@\tIN\tNS\tns.%s.\n", zone)
	if !hasName(cfg.Records, "ns") {
		b.WriteString("ns\tIN\tA\t127.0.0.1\n")
	}
	for _, r := range cfg.Records {
		emitRecord(&b, r)
	}
	return b.String()
}

func emitRecord(b *strings.Builder, r records.Record) {
	ttlCol := ""
	if r.TTL > 0 {
		ttlCol = fmt.Sprintf("%d\t", r.TTL)
	}
	value := r.Value
	if strings.EqualFold(r.Type, "CNAME") {
		value = cnameTarget(r.Value)
	}
	fmt.Fprintf(b, "%s\t%sIN\t%s\t%s\n", r.Name, ttlCol, strings.ToUpper(r.Type), value)
}

// cnameTarget formats a CNAME value: a bare label stays relative to $ORIGIN,
// anything with a dot is emitted as a fully qualified name (trailing dot).
func cnameTarget(value string) string {
	v := strings.TrimSuffix(strings.TrimSpace(value), ".")
	if !strings.Contains(v, ".") {
		return v
	}
	return v + "."
}

func hasName(recs []records.Record, name string) bool {
	for _, r := range recs {
		if r.Name == name {
			return true
		}
	}
	return false
}

// Corefile renders a CoreDNS Corefile for cfg. zoneFile is the path CoreDNS
// reads the zone from, relative to CoreDNS's working directory.
func Corefile(cfg *records.Config, zoneFile string) string {
	port := cfg.ResolvedPort()
	upstreams := strings.Join(cfg.ResolvedUpstreams(), " ")

	bind := ""
	if a := strings.TrimSpace(cfg.Address); a != "" && a != "0.0.0.0" {
		bind = fmt.Sprintf("    bind %s\n", a)
	}

	var b strings.Builder
	b.WriteString("# Generated by devdns -- do not edit by hand.\n")
	b.WriteString("# Edit records.yaml and run `devdns generate` instead.\n\n")

	// Authoritative server block for the local development zone.
	fmt.Fprintf(&b, "%s:%d {\n", cfg.Zone, port)
	b.WriteString(bind)
	fmt.Fprintf(&b, "    file %s {\n", zoneFile)
	b.WriteString("        reload 5s\n")
	b.WriteString("    }\n")
	b.WriteString("    log\n")
	b.WriteString("    errors\n")
	b.WriteString("}\n\n")

	// Catch-all block: forward everything else to the upstream resolvers.
	fmt.Fprintf(&b, ".:%d {\n", port)
	b.WriteString(bind)
	fmt.Fprintf(&b, "    forward . %s\n", upstreams)
	b.WriteString("    cache 30\n")
	b.WriteString("    reload 5s\n")
	b.WriteString("    log\n")
	b.WriteString("    errors\n")
	b.WriteString("}\n")
	return b.String()
}
